
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 15 21:44:09 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 15;
  public static final int INCREMENT = 37;
  public static final int GREATER_OR_EQUAL = 9;
  public static final int CONST = 22;
  public static final int CHAR_LITERAL = 4;
  public static final int NOT_EQUAL = 7;
  public static final int CONTINUE = 32;
  public static final int DECREMENT = 38;
  public static final int MINUS = 13;
  public static final int GREATER_THAN = 8;
  public static final int SEMICOLON = 39;
  public static final int AND = 34;
  public static final int LESS_OR_EQUAL = 11;
  public static final int EQUAL_LOGIC = 6;
  public static final int OR = 35;
  public static final int COMMA = 41;
  public static final int CLASS = 19;
  public static final int PLUS = 12;
  public static final int MULTIPLY = 14;
  public static final int IF = 23;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int RETURN = 29;
  public static final int EQUAL_ASSIGN = 36;
  public static final int LAMBDA = 49;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int PROGRAM = 17;
  public static final int OPEN_BRACE = 47;
  public static final int MOD = 16;
  public static final int CLOSE_BRACKET = 46;
  public static final int OPEN_BRACKET = 45;
  public static final int BREAK = 18;
  public static final int IDENT = 2;
  public static final int VOID = 30;
  public static final int OPEN_PARENTHESIS = 43;
  public static final int COLON = 40;
  public static final int FOREACH = 33;
  public static final int ELSE = 21;
  public static final int ENUM = 20;
  public static final int READ = 28;
  public static final int WHILE = 25;
  public static final int EXTENDS = 31;
  public static final int CLOSE_BRACE = 48;
  public static final int CLOSE_PARENTHESIS = 44;
  public static final int LESS_THAN = 10;
  public static final int PRINT = 27;
  public static final int DO = 24;
  public static final int BOOL_LITERAL = 5;
  public static final int INT_LITERAL = 3;
}

